### ISSUE TITLE
Deploying "core" on Avalance > Fuji

### ISSUE THREAD

**Issue by GildedHonour** [GildedHonour/traderjoe-xyz_description#1]
**joe-core**

As the documentation suggests, I do this:

```
npx hardhat node
```
but will get this:

![Screenshot_2022-01-16_13-25-44](https://user-images.githubusercontent.com/2032888/149668597-b532d866-cda8-4407-8e9d-b86985395cf3.png)

**Comment by GildedHonour** [comment]
Obtained API key of Infura
Specified a mnemonic phrase of a temporaly wallet at myetherwallet.com

But:

```
$ yarn ropsten:deploy


yarn run v1.22.17
warning ../../../../package.json: No license field
$ hardhat --network ropsten deploy
Compiling 53 files with 0.6.12


[.........]


Compilation finished successfully
Creating Typechain artifacts in directory types for target ethers-v5
Successfully generated Typechain artifacts!
An unexpected error occurred:

Error: ERROR processing /home/alex/projects/blockchain/traderjoe-xyz/joe-core/deploy/MasterChefJoeV2.js:
Error: No Contract deployed with name JoeToken
    at Object.getContract (/home/alex/projects/blockchain/traderjoe-xyz/joe-core/node_modules/hardhat-deploy-ethers/src/internal/helpers.ts:444:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.module.exports [as func] (/home/alex/projects/blockchain/traderjoe-xyz/joe-core/deploy/MasterChefJoeV2.js:6:15)
    at DeploymentsManager.executeDeployScripts (/home/alex/projects/blockchain/traderjoe-xyz/joe-core/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1011:22)
[.........]
```

**Comment by GildedHonour** [comment]
the **.env** file


```
ALCHEMY_API_KEY=
COINMARKETCAP_API_KEY=
ETHERSCAN_API_KEY=
FORKING=false
HARDHAT_NETWORK=ropsten
HARDHAT_MAX_MEMORY=4096
HARDHAT_SHOW_STACK_TRACES=true
HARDHAT_VERBOSE=true
INFURA_API_KEY="[real api key]"
MNEMONIC="[...real phrase .... ]"
REPORT_GAS=false
TENDERLY_PROJECT=
TENDERLY_USERNAME=
FEEDER_PRIVATE_KEY=
FEEDER_PUBLIC_KEY=
```

**Comment by GildedHonour** [comment]
Running this

    npx hardhat node --fork https://eth-mainnet.alchemyapi.io/v2/<real api key here>

will result in the same error

**Comment by GildedHonour** [comment]
https://github.com/traderjoe-xyz/joe-core/issues/20

**Comment by GildedHonour** [comment]
yarn test

===>


![Screenshot_2022-01-20_10-23-44](https://user-images.githubusercontent.com/2032888/150347269-9c75ba3c-639f-403e-851b-e3019a7feb1f.png)

**Comment by zakrian07** [comment]
did you figure out anything with this ?

**Comment by GildedHonour** [comment]
Uncommented the exported modules in `deploy/`
Then

```
yarn fuji:deploy
```
===>


```
Nothing to compile
Creating Typechain artifacts in directory types for target ethers-v5
Successfully generated Typechain artifacts!
deploying "JoeFactory"An unexpected error occurred:

Error: ERROR processing /home/alex/projects/blockchain/traderjoe-xyz/joe-core/deploy/JoeFactory.js:
Error: insufficient funds for intrinsic transaction cost (error={"name":"ProviderError","code":-32000,"_isProviderError":true}, method="sendTransaction", transaction=undefined, code=INSUFFICIENT_FUNDS, version=providers/5.5.0)

```

I went to **faucet.avax-test.network/** and requested airdrop at 0xc79A395cE054B9F3B73b82C4084417CA9291BC87 


![Screenshot_2022-01-24_08-19-03](https://user-images.githubusercontent.com/2032888/150773636-6cd88152-c5d6-49ce-8e90-2d0de649ba1a.png)


but  it didn't work, it returned an error, without a meanful description

**Comment by GildedHonour** [comment]
Also, I've tried to specify the minimal gas price - still didn't help

```
    fuji: {
      url: "https://api.avax-test.network/ext/bc/C/rpc",
      accounts,
      chainId: 43113,
      live: true,
      saveDeployments: true,
      tags: ["staging"],
      // gasMultiplier: 2,
      
      gasPrice: 25000000000

    },
```

**Comment by zakrian07** [comment]
is this deployed on hardhat ?
which network MNEMONIC you are using?

**Comment by GildedHonour** [comment]
I created a new AVAX account and got airdrop successfully, but the error still:

```
Error: insufficient funds for intrinsic transaction cost (error={"name":"ProviderError","code":-32000,"_isProviderError":true}, method="sendTransaction", transaction=undefined, code=INSUFFICIENT_FUNDS, version=providers/5.5.0)
```

**Comment by GildedHonour** [comment]
I've tried polygon mumbai, with airdrop - same "insufficient funds"
 Probably it uses not the account from the mnemonic phrase, but some other.
 
Account I'm using, at avalanche testnet - https://testnet.snowtrace.io/address/0xd3f5e28817238f38c934e6c2966feefc62c6afed

**Comment by GildedHonour** [comment]
**joe-core**

Partially deployed. 

The error implies that there's a mistake in the original code

![Screenshot_2022-01-25_11-15-36](https://user-images.githubusercontent.com/2032888/150993595-f5370774-542f-4dee-a60e-9de89adda2a5.png)

**Comment by GildedHonour** [comment]
**joe-lending**

also partially deployed, and fails due to, probably, a mistake in the code too

![Screenshot_2022-01-25_11-32-01](https://user-images.githubusercontent.com/2032888/150996467-d3001923-a35a-4969-84d2-668e1eb24f94.png)

**Comment by GildedHonour** [comment]
**joe-core**


file: `./joe-core/deploy/MasterChefJoeV3.js`

(1) 
this call cases an exception:

```
await dummyToken.renounceOwnership();
```

===>

```
Error: ERROR processing /home/alex/projects/blockchain/traderjoe-xyz/joe-core/deploy/MasterChefJoeV3.js:
Error: cannot estimate gas; transaction may fail or may require manual gas limit (error={"name":"ProviderError","code":3,"_isProviderError":true,"data":"0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000204f776e61626c653a2063616c6c6572206973206e6f7420746865206f776e6572"}, method="estimateGas", transaction={"from":"0xACA58f5C5AA23aa5e27F523d2c64041397425c4a","to":"0xD99B5888257704D8bB7883cA1aD83F0CE43e7ec0","data":"0x715018a6","accessList":null}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.5.0)
```

`dummyToken` isn't null, and its `address` has a value



(2)

after commenting it out

```
// await dummyToken.renounceOwnership();
```

this call this make another exception emerge:

```
  await (await MCV2.add(100, dummyToken.address, false)).wait();
```

===>
```
An unexpected error occurred:

Error: ERROR processing /home/alex/projects/blockchain/traderjoe-xyz/joe-core/deploy/MasterChefJoeV3.js:
Error: invalid address or ENS name (argument="name", value=false, code=INVALID_ARGUMENT, version=contracts/5.5.0)
```

The `MasterChefJoeV2.add()` and `MasterChefJoeV3.add()` functions:

```
    function add(
        uint256 _allocPoint,
        IERC20 _lpToken,
        IRewarder _rewarder       //interface, not a boolean
    ) public onlyOwner { ....
```

which implies that the 3rd argument passed, likely, into it -- `false` -- causes the exception

**Comment by GildedHonour** [comment]
The `MasterChefJoe.add()` function:

```
function add(uint256 _allocPoint, IERC20 _lpToken) public onlyOwner {
```

The `MasterChef.add()` function:
```
    function add(
        uint256 _allocPoint,
        IERC20 _lpToken,
        bool _withUpdate    //notice a boolean
    ) public onlyOwner {
```

**Comment by GildedHonour** [comment]
Trying to fix this:

```
  await (await MCV2.add(100, dummyToken.address, false)).wait();  // the "false" is a wrong parameter
```

**(1)** Using  `0x00000....` the address of the rewarder

```
  await (await MCV2.add(100, dummyToken.address, 0x0000000000000000000000000000000000000000)).wait();

 ===> 

error: can't estimate gas...
```



**(2)** Using the address of dummyToken:
```
  await (await mcv2.add(100, dummyToken.address, dummyToken.address)).wait();
```
will pass through; but

```
ReferenceError: rewarder is not defined

```

because the variable `rewarder` hasn't been defined anywhere, in this code:
```
 await rewarder.init(dummyToken.address, {
    gasLimit: 245000,
  });
```

**Comment by GildedHonour** [comment]
JoeToken on the Avalanche mainnet:

https://snowtrace.io/token/0x6e84a6216eA6dACC71eE8E6b0a5B7322EEbC0fDd


contract:
https://snowtrace.io/address/0x6e84a6216ea6dacc71ee8e6b0a5b7322eebc0fdd#code


nothing helpful to gather from there, nor anything about "reward" in its source code;

**Comment by GildedHonour** [comment]
In "./rewarders" directory there're 4 contracts that implement `IRewarder`, but none is not used anywhere in the project at all. How to use any of them then?

**Comment by GildedHonour** [comment]
In `./test` directory there's some helpful stuff

**Comment by GildedHonour** [comment]
deployed  `SimpleRewarderPerBlock`; still the error - "can't estimate gas"
![Screenshot_2022-02-03_15-41-21](https://user-images.githubusercontent.com/2032888/152407916-a2fac9ce-e9a5-4fb4-8553-421ec30df15b.png)

===>
![Screenshot_2022-02-03_15-42-47](https://user-images.githubusercontent.com/2032888/152408018-0ed9d34a-d1ce-4ff5-9872-7097eecbb09b.png)

**Comment by GildedHonour** [comment]
MasterChefJoeV3 on mainnet: 

https://snowtrace.io/address/0x188bed1968b795d5c9022f6a0bb5931ac4c18f00

---
https://docs.traderjoexyz.com/main/security-and-contracts/contracts

**Comment by GildedHonour** [comment]
The order in which they get deployed may be important and cause those errors. 

There exists `SimpleRewarderPerSec.js` which goes after `MasterChefJoeV3`. 

There's also `module.exports.dependencies` but `MasterChefJoeV3` doesn't include `SimpleRewarderPerSec` in its list

**Comment by GildedHonour** [comment]
created `./deploy2` directory and moved all the content of `./deploy` into it;
moving back each file into `deploy` thus deploying it one by one

**Comment by GildedHonour** [comment]
* JoeVote (error)
    * FarmLens (error; also depends on MasterChefJoeV3)
    * JoeMakerV2
    * JoeMakerV3
    * JoeRoll
    * JoeVote (error)
    * MasterChefJoe
    * MasterChefJoeV2
    * MasterChefJoeV3 (error)
    * MasterChefRewarderPerBlock (error)
    * SimpleRewarderPerSec (error)
    * Zap (error)

Some of the those that cause errors contain hard-coded addresses in them. For instance, `MasterChefRewarderPerBlock.js`:

```
  const lpTokenAddress = "0x6d551ad3570888d49da4d6c8b8a626c8cbfd5ac2"; // WAVAX-USDT on Rinkeby
 ```
namely, this LP token isn't on avax

**Comment by GildedHonour** [comment]
this hardcoded address:
```
  // ./deploy/MasterChefRewarderPerBlock.js
  const lpTokenAddress = "0x6d551ad3570888d49da4d6c8b8a626c8cbfd5ac2"; // WAVAX-USDT on Rinkeby

```
corresponds to this:

```
        Joe LP Token (JLP) > JoeERC20 > joe-core/contracts/traderjoe/JoeERC20.sol
```

has to be deployed and its address will have to used in place of the one above

**Comment by GildedHonour** [comment]
deployed `Joe LP Token (JLP) > JoeERC20` ==> **0xF7Cd6FEB33Df1300121F4a757BaA25CA06B8D3EA**

**Comment by GildedHonour** [comment]
**./deploy/JoeVote.js:**
```

const JOE_AVAX_LP = new Map();

JOE_AVAX_LP.set("4", "0xab9ba8c7e7b00381027061a8506d895e8938060b");
JOE_AVAX_LP.set("43113", "0xF7Cd6FEB33Df1300121F4a757BaA25CA06B8D3EA");  //add this

```

**JoeVote** - deployed

**Comment by GildedHonour** [comment]
**./deploy/MasterChefRewarderPerBlock.js**
```

  // comment it out
  // const lpTokenAddress = "0x6d551ad3570888d49da4d6c8b8a626c8cbfd5ac2"; // WAVAX-USDT on Rinkeby

  // add this
  const lpTokenAddress = "0xF7Cd6FEB33Df1300121F4a757BaA25CA06B8D3EA"; WAVAX-USDT on Avalanche > Fuji

```

**MasterChefRewarderPerBlock** - deployed

**Comment by GildedHonour** [comment]
**./deploy/Zap.js**

```
 await zap.initialize(joe.address, router.address); //will cause an error
```

this will begin to cause  exceptions after 1st deployment process - when called a 2nd, 3rd... times

**Comment by GildedHonour** [comment]
All the contracts but **FarmLens**  have been deployed

**Comment by GildedHonour** [comment]
```
//WAVAX on Avalanche > Fuji
const rewardToken = "0xd00ae08403B9bbb9124bB305C09058E32C39A48c";


// WAVAX-USDT on Avalanche > Fuji
const lpToken = "0xF7Cd6FEB33Df1300121F4a757BaA25CA06B8D3EA";

```

**Comment by GildedHonour** [comment]
joe-core/deploy/FarmLens.js

These 3 addresses are  `JoePair` tokens: 
  *  WAVAX-USDT 
  * WAVAX-USDC
  * WAVAX-DAI

![Screenshot_2022-02-05_13-45-34](https://user-images.githubusercontent.com/2032888/152650659-3a095c04-233e-4c75-bd89-900216d77472.png)


They're on Avalance Mainnet. The task is find USDT, USDC and DAI on Fuji, if they exist there at all; if not - deploy them


---

WAVAX-USDT --> deployed by me earlier -> 0xF7Cd6FEB33Df1300121F4a757BaA25CA06B8D3EA
it may be wrong because it's JoeERC20, but it should be JoePair instead

**Comment by GildedHonour** [comment]
**deploy/MasterChefRewarderPerBlock.js:**

sometimes, but not always, it'll throw an exception 

```
Error: ERROR processing /home/alex/projects/blockchain/traderjoe-xyz/joe-core/deploy/MasterChefRewarderPerBlock.js:
Error: nonce has already been used (error={"name":"ProviderError","code":-32000,"_isProviderError":true}, method="sendTransaction", transaction=undefined, code=NONCE_EXPIRED, version=providers/5.5.0)

```

**Comment by GildedHonour** [comment]
https://github.com/GildedHonour/joe-core , br. avalanche_fuji_deploy

**Comment by GildedHonour** [comment]
**deploy/FarmLens.js**

There's a mistake here:
```

  if (chainId === "43114") {
    wavaxUsdtAddress = address("0xeD8CBD9F0cE3C6986b22002F03c6475CEb7a6256");
    wavaxUsdcAddress = address("0x87Dee1cC9FFd464B79e058ba20387c1984aed86a");  // error - this is really WAVAX-DAI
    wavaxDaiAddress = address("0xA389f9430876455C36478DeEa9769B7Ca4E3DDB1");  // error - this is really WAVAX-USDC
  }
```

The addresses of wavaxUsdcAddress and wavaxDaiAddress should be swaped.

**Comment by GildedHonour** [comment]
Deploying `JoePair` contracts on Fuji:

```
WAVAX-USDT:
0x883eb5e72bc957d6caD87B07D0aEf771485c8F66

WAVAX-USDC:
0x39d88cF0B7d15A7C0DE4ad7897a9b8763314d3eC

WAVAX-DAI:
0xE48Fd4b1F065088C5eDdE7c114a2355Cfff869Cd
```

**Comment by GildedHonour** [comment]
Actually, more corect way to create pairs is by calling `JoeFactory.createPair(..)`:

```
WAVAX-USDC:
0x5bc94145def1d0034fa08d64eff59e72b3a4f41d

WAVAX-USDT:
0x5528f1355c070682a2B079a5dCA8129F568271Af

WAVAX-DAI:
0xCD4CF44B29cC8150F67A6447929C7B9f89d51827
```

**Comment by GildedHonour** [comment]
**FarmLens** has been deplloyed

**Comment by GildedHonour** [comment]
All the existsing tests, but one, in "core" have passed.


![Screenshot_2022-02-10_14-27-46](https://user-images.githubusercontent.com/2032888/153462881-5731a721-4eb6-414e-87f9-df66eab514e2.png)


StableJoeStaking.test.js > "should allow setting a new deposit fee, only by owner" -- failed

**Comment by GildedHonour** [comment]
These initially initially existed on mainnet only:

THORSMEAD:
https://snowtrace.io/address/0x245c2591403e182e41d7a851eab53b01854844ce  


JoePair (WAVAX, THORSMEAD):
https://snowtrace.io/address/0xb97f23a9e289b5f5e8732b6e20df087977acc434 



I've deployed them on Fuji:

THORSMEAD:
https://testnet.snowtrace.io/address/0xe9e29cb769786360d9fd55743478bc8fa0b87542


JoePair (WAVAX, THORSMEAD):
https://testnet.snowtrace.io/address/0x0e65184bBc7e47De8D8C5Fe3D1AdC070B5b7574A 


These are used by `SimpleRewarderPerSec.js` as `lpToken`

The code for `THORSMEAD` has been taken from Avalanche mainnet explorer.

**Comment by GildedHonour** [comment]
The code of `THORSMEAD` on  Avalanche mainnet explorer contains  some hardcode addresses:

https://snowtrace.io/address/0x245c2591403e182e41d7a851eab53b01854844ce#code

```

    //1
    // bnb address of the charity wallet
    address private _charityWalletAddress = 0x8a9c04eF43F82113AAe56C8880F5e7E733941aA9;

    //2
    // bnb address of the contract owner
   _owner = 0x43C4b25EB0d20F3E344c5dBb3ffFFb7a6D4a0301;   

```
